#!/usr/bin/env bash
# SOURCE
# to instantiate with this, add:
# tmp=`pwd`; # cd SUB_PATH/ && . sub-init && cd $tmp
# to your bashrc

_sub_resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

_sub_abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"
  
  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(_sub_resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

_sub_source() {
  local out=`grep $'#[ \t]*SOURCE' $1`
  if [ "$out" == "" ]; then
    echo "0"
    return
  fi
  echo "1"
}

export SUB_PATH=`pwd`

case "$0" in
bash | zsh)
  source ../completions/sub.$0
  ;;
-bash )
  source ../completions/sub.bash
  ;;
esac

function sub() {
    local original_path=$PATH
    local source_command=0
    export PATH="$SUB_PATH:$PATH"

    libexec_path=$SUB_PATH

    command="$1"
    case "$command" in
    "" | "-h" | "--help" )
      sub-help
      ;;
    * )
      command_path="$(command -v "sub-$command" || true)"
      if [ ! -x "$command_path" ]; then
        echo "sub: no such command \`$command'"
      else
          source_command=$(_sub_source $command_path)
          shift
          if [[ "$1" -eq "--complete" ]]; then
              $command_path "$@"
          elif [[ "$source_command" -eq 0 ]]; then
              $command_path "$@"
          else 
              . $command_path "$@"
          fi
      fi
      ;;
    esac
    export PATH=$original_path
}
